version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: hoge
          command: |
            echo "A=B" >> $BASH_ENV
      - run:
          name: test
          command: |
            echo "CIRCLE_BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "CIRCLE_PR_REPONAME: ${CIRCLE_PR_REPONAME}"
            echo "CIRCLE_PR_USERNAME: ${CIRCLE_PR_USERNAME}"
            echo "CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}"
            echo "CIRCLE_PROJECT_USERNAME: ${CIRCLE_PROJECT_USERNAME}"

workflows:
  version: 2
  test:
    jobs:
      - build
