version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.11
    steps:
      - run:
          name: test
          command: |
            echo '1'
            echo 'echo ${CIRCLE_PULL_REQUEST}'
            echo ${CIRCLE_PULL_REQUEST}
            echo 'echo ${CIRCLE_PULL_REQUESTS}'
            echo ${CIRCLE_PULL_REQUESTS}

workflows:
  version: 2
  test:
    jobs:
      - build
