version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: hoge
          command: |
            echo "A=B" >> $BASH_ENV
      - run:
          name: test
          command: |
            echo '4'
            source $BASH_ENV
            echo 'echo ${CIRCLE_PULL_REQUEST}'
            echo ${CIRCLE_PULL_REQUEST}
            echo 'echo ${CIRCLE_PULL_REQUESTS}'
            echo ${CIRCLE_PULL_REQUESTS}
            echo 'echo ${CI_PULL_REQUEST}'
            echo ${CI_PULL_REQUEST}
            echo 'echo ${CIRCLE_PR_NUMBER}'
            echo ${CIRCLE_PR_NUMBER}

workflows:
  version: 2
  test:
    jobs:
      - build
